FROM ubuntu:devel

RUN apt-get update &&  apt-get install  -y build-essential zlib1g-dev libncurses5-dev libncursesw5-dev git wget unzip python-pip python-dev

# Install procps (to get free and top)
RUN apt-get install -y procps

# Install Bowtie2-2.3.4.3
RUN apt-get install -y libtbb-dev && \
	mkdir /src && \
	cd /src && \
	wget -O bowtie2.zip https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.4.3/bowtie2-2.3.4.3-linux-x86_64.zip/download && \
	unzip bowtie2.zip && \
  rm bowtie2.zip && \
	ln -s /src/bowtie2-2.3.4.3/bowtie2* /usr/local/bin

# Install Bismark-0.20.0
RUN cd /src && \
	wget https://github.com/FelixKrueger/Bismark/archive/0.20.0.tar.gz && \
	tar zxf 0.20.0.tar.gz && \
  rm 0.20.0.tar.gz && \
	ln -s /src/Bismark-0.20.0/bismark* /usr/local/bin/

# Install samtools-1.3.1
RUN cd /src && \
    wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2 && \
    tar -vxjf samtools-1.3.1.tar.bz2 && \
    rm samtools-1.3.1.tar.bz2 && \
    cd samtools-1.3.1 && \
    make && \
    ln -s /src/samtools-1.3.1/samtools /usr/local/bin

# Install cutadapt-1.18 (for Trimgalore)
RUN pip install cutadapt==1.18

# Install openjdk-8
RUN apt-get -y install openjdk-8-jre

# Install FastQC-0.11.8 
RUN cd /src && \
    wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.8.zip && \
    unzip fastqc_v0.11.8.zip && \
    rm fastqc_v0.11.8.zip && \
    chmod 755 FastQC/fastqc && \
    ln -s /src/FastQC/fastqc /usr/local/bin

# Install Trimgalore-0.5.0
RUN cd /tmp && \
    wget https://github.com/FelixKrueger/TrimGalore/archive/0.5.0.zip && \
    unzip 0.5.0.zip && \
    cp TrimGalore-0.5.0/trim_galore /usr/local/bin && \
    chmod 755 /usr/local/bin/trim_galore

# Install multiQC-1.6
RUN pip install multiQC==1.6

# Clean up TMP
RUN rm -rf tmp
